kernel:
  image: linuxkit/kernel:4.14.40
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:v0.4
  - linuxkit/runc:v0.4
  - linuxkit/containerd:v0.4
  - linuxkit/ca-certificates:v0.4
  - linuxkit/getty:v0.4
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.4
  - name: sysfs
    image: linuxkit/sysfs:v0.4
  - name: format
    image: linuxkit/format:v0.4
  - name: mount
    image: linuxkit/mount:v0.4
    command: ["/usr/bin/mountie", "/var/lib/docker"]
  - name: rngd-oneshot
    image: linuxkit/rngd:v0.4
    command: ["rngd", "-1"]
services:
  #- name: getty
  #image: linuxkit/getty:v0.4
  # env:
  #  - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:v0.4
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.4
  - name: ntpd
    image: linuxkit/openntpd:v0.4
  - name: docker
    image: docker:17.09.0-ce-dind
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /var/lib/docker:/var/lib/docker
     - /lib/modules:/lib/modules
     - /etc/docker/daemon.json:/etc/docker/daemon.json
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
files:
  - path: var/lib/docker
    directory: true
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
trust:
  org:
    - linuxkit
    - library
